# Generated by Django 6.0.1 on 2026-02-04 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('nearest_office', models.CharField(choices=[('kathmandu', 'Kathmandu'), ('pokhara', 'Pokhara'), ('dharan', 'Dharan'), ('butwal', 'Butwal'), ('chitwan', 'Chitwan')], max_length=20)),
                ('question_regarding', models.CharField(choices=[('course', 'Course'), ('visa', 'Visa'), ('preparation', 'Language Preparation'), ('testvoucher', 'English Test Voucher'), ('documentation', 'Financial Documentation'), ('borderupdates', 'Border Updates')], max_length=20)),
                ('destination_country', models.CharField(choices=[('australia', 'Australia'), ('uk', 'United Kingdom'), ('usa', 'USA'), ('canada', 'Canada'), ('newzealand', 'New Zealand'), ('help', 'Help Me Decide')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
